### ISSUE TITLE
Doesn't Work in Swift 2.0

### ISSUE THREAD

**Issue by btelintelo** [Daniel1of1/CSwiftV#1]

**Comment by ulfie22** [comment]
I updated this super useful library to Swift2 and put in a pull request. Until it is accepted, you can grab it at:

https://github.com/ulfie22/CSwiftV

**Comment by Daniel1of1** [comment]
Hi Thanks very much for this. Sorry for taking so long to get round to the PR #2. So 2.0 code is at [0.0.3](https://github.com/Daniel1of1/CSwiftV/releases/tag/0.0.3) and is pushed to CocoaPods too.
