### ISSUE TITLE
Swift 3 Compatibility

### ISSUE THREAD

**Issue by cbarrerah** [Daniel1of1/CSwiftV#17]
Hi,

I'm using your wonderful csv parser for a class asignment, but as i had to make it cross compilable to linux, i had to use the latest dev branch of swift 3. I modified your code to make it compliant to the new version, are you already updating your code, or would you like me to send the changes?

Thanks

**Comment by Daniel1of1** [comment]
Thank you very much 😃. Yes please open a PR and I'll take a look at it. I've not yet made any updates for swift 3 so I'd really appreciate the updates 👍

**Comment by cbarrerah** [comment]
Ok, i'll admit it. I'm a git noob XD

Any link to learn about pull requests?

I understand that is a way for anyone to ask for approval of code changes by the maintainer. My understanding is the steps to do so are:
- Clone repository on local machine
- New branch to commit changes
- Update files 
- Commit changes to local branch
- Ask for a pull request 

When i do so, github says: "You may not have permission to access CSwiftV. Check Preferences to make sure you’re still logged in." 

So maybe i did something wrong, any obvious mistake that you can notice?

**Comment by cbarrerah** [comment]
Ok, maybe i made a mess, but i think i created the pull requests correctly.

**Comment by cbarrerah** [comment]
I had to compile it in Linux for my project, so had to make some messy modifications to make it work with the current limitations of the API. I'll create another pull request when i can and you can evaluate if is worth the mess to be able to crosscompile in OSX and Linux.

**Comment by Daniel1of1** [comment]
Done! Thankyou @shadowcharly  and @notronik (#18,#19,#21)
