### ISSUE TITLE
0.0.6 tag for Swift 3.0

### ISSUE THREAD

**Issue by noahemmet** [Daniel1of1/CSwiftV#25]
Would you mind tagging the latest release as `0.0.6`? CSwiftV isn't compiling on the latest Swift dev release. (Here's the tag in my fork: https://github.com/noahemmet/CSwiftV/releases/tag/0.0.6)

**Comment by Daniel1of1** [comment]
sure - it's now there. 👍, was this for use with SwiftPM?

**Comment by noahemmet** [comment]
Thanks so much—it sure was!
