### ISSUE TITLE
Cocoapods release 0.0.6

### ISSUE THREAD

**Issue by kevinmanase** [Daniel1of1/CSwiftV#29]
I am unable to point to 0.0.6. it seems like 0.0.5 is the latest available. Can you please fix this?
I'm having issues with Swift 3. Would love to keep it as a pod not add manually.
Thanks

**Comment by thully** [comment]
I worked around this by including it as a pod and copying the latest CSwiftV code over the outdated code it downloads. That obviously isn't a solution, but it is a functional workaround for the time being.

**Comment by Daniel1of1** [comment]
will get onto this but for the time being I can offer perhaps a more effective workaround which is to point to a specific commit (just in case you weren't aware) , 

``` ruby
pod 'CSwiftV', :git => 'https://github.com/Daniel1of1/CSwiftV.git', :commit => 'e43e381'
```

more information here: https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo

**Comment by Daniel1of1** [comment]
0.0.7 is now pushed to trunk.
