### ISSUE TITLE
Tag Swift 2.0 release

### ISSUE THREAD

**Issue by cbowns** [Daniel1of1/CSwiftV#3]
I want to use CSwiftV in a project, but I'd like to pin it to a tag that includes Swift 2 support. I'll send a PR with a Podfile update once there's a tag to anchor it to.

**Comment by Daniel1of1** [comment]
Hey thanks for that, sorry for not being on top of this [0.0.3](https://github.com/Daniel1of1/CSwiftV/releases/tag/0.0.3) is up now with 2.0 code, also pushed to trunk.

**Comment by Daniel1of1** [comment]
I'll close this but please reopen if there is an issue :smile:
