### ISSUE TITLE
0.0.7 tag for SPM fix

### ISSUE THREAD

**Issue by noahemmet** [Daniel1of1/CSwiftV#33]
Hey, me again! Looks like https://github.com/Daniel1of1/CSwiftV/pull/32 fixes the SPM error I'm currently seeing; would you mind pushing another release please?

(Alternately, is there a way for SPM to target a specific commit? I haven't been able to find one.)

**Comment by Daniel1of1** [comment]
Hey! , good point, don't think there is... I've just tagged and pushed `0.0.7` for `a1a04d3`.
