### ISSUE TITLE
CocoaPods release

### ISSUE THREAD

**Issue by stel** [Daniel1of1/CSwiftV#34]
Hey @Daniel1of1! It would be great to release v0.0.7 on CocoaPods in order to be able to use it as a dependency via Podspecs because there is no option to specify git tag/commit/branch there.

**Comment by Daniel1of1** [comment]
@stel - done - https://cocoapods.org/pods/CSwiftV :) thanks for the issue, let me know if everything's working properly then I'll close.

**Comment by stel** [comment]
Awesome @Daniel1of1, thanks a lot! Everything works perfectly. I think you can also close https://github.com/Daniel1of1/CSwiftV/issues/29 :)
